# Generated by Django 5.2.3 on 2025-06-30 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_remove_patient_pesel_search_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('oczekiwanie', 'Oczekiwanie'), ('przyjęte_do_realizacji', 'Przyjęte do realizacji'), ('wystawiono_skierowanie', 'Wystawiono skierowanie'), ('badania_w_toku', 'Badania w toku'), ('wizyta_odbyta', 'Wizyta odbyta'), ('interwencja', 'Interwencja'), ('zakończone', 'Zakończone'), ('odwołane', 'Odwołane')], max_length=50, unique=True, verbose_name='Nazwa statusu')),
                ('order_sequence', models.PositiveIntegerField(help_text='Kolejność wyświetlania statusów', verbose_name='Kolejność')),
                ('allows_transition_to', models.JSONField(default=list, help_text='Lista statusów na które można przejść z tego statusu', verbose_name='Dozwolone przejścia statusów')),
            ],
            options={
                'verbose_name': 'Typ statusu',
                'verbose_name_plural': 'Typy statusów',
                'db_table': 'tenant_schema_statustypes',
                'ordering': ['order_sequence'],
            },
        ),
        migrations.CreateModel(
            name='VisitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa typu wizyty')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
            ],
            options={
                'verbose_name': 'Typ wizyty',
                'verbose_name_plural': 'Typy wizyt',
                'db_table': 'tenant_schema_visittypes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VisitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire_location', models.CharField(blank=True, choices=[('ikp', 'IKP'), ('poz', 'POZ')], max_length=10, null=True, verbose_name='Miejsce wypełnienia ankiety')),
                ('questionnaire_date', models.DateField(blank=True, null=True, verbose_name='Data wypełnienia ankiety')),
                ('accepted_for_realization_date', models.DateField(blank=True, null=True, verbose_name='Data przyjęcia do realizacji')),
                ('referral_issued_date', models.DateField(blank=True, null=True, verbose_name='Data wystawienia skierowania')),
                ('referral_expires_date', models.DateField(blank=True, null=True, verbose_name='Data ważności skierowania')),
                ('visit_completed_date', models.DateField(blank=True, null=True, verbose_name='Data odbycia wizyty')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Komentarze')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Anulowana')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data ostatniej aktualizacji')),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_visits', to=settings.AUTH_USER_MODEL, verbose_name='Koordynator')),
                ('current_responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_visits', to=settings.AUTH_USER_MODEL, verbose_name='Aktualnie odpowiedzialny')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_cards', to='patients.patient', verbose_name='Pacjent')),
                ('questionnaire_completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_questionnaires', to=settings.AUTH_USER_MODEL, verbose_name='Ankietę wypełnił')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_cards', to='visits.statustype', verbose_name='Status')),
                ('visit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_cards', to='visits.visittype', verbose_name='Typ wizyty')),
            ],
            options={
                'verbose_name': 'Karta wizyty',
                'verbose_name_plural': 'Karty wizyt',
                'db_table': 'tenant_schema_visitcards',
                'ordering': ['-created_at'],
            },
        ),
    ]
