# Generated by Django 5.2.3 on 2025-07-02 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statustype',
            options={'verbose_name': 'Typ statusu', 'verbose_name_plural': 'Typy statusów'},
        ),
        migrations.RemoveField(
            model_name='statustype',
            name='allows_transition_to',
        ),
        migrations.RemoveField(
            model_name='statustype',
            name='order_sequence',
        ),
    ]
