# Generated by Django 5.2.3 on 2025-07-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_alter_statustype_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitcard',
            name='status',
        ),
        migrations.AddField(
            model_name='visitcard',
            name='visit_status',
            field=models.CharField(choices=[('oczekiwanie', 'Oczekiwanie'), ('przyjęte_do_realizacji', 'Przyjęte do realizacji'), ('wystawiono_skierowanie', 'Wystawiono skierowanie'), ('badania_w_toku', 'Badania w toku'), ('wizyta_odbyta', 'Wizyta odbyta'), ('interwencja', 'Interwencja'), ('zakończone', 'Zakończone'), ('odwołane', 'Odwołane')], default='oczekiwanie', max_length=25, verbose_name='Status karty'),
        ),
        migrations.DeleteModel(
            name='StatusType',
        ),
    ]
