# Generated by Django 5.2.3 on 2025-07-07 09:01

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EwusAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('6e4469f3-8385-4431-a5b2-25f3616c14fc'), editable=False, primary_key=True, serialize=False)),
                ('login', encrypted_model_fields.fields.EncryptedCharField(verbose_name='zaszyfrowany login do ewuś')),
                ('password', encrypted_model_fields.fields.EncryptedCharField(verbose_name='zaszyfrowane hasło do ewuś')),
                ('doctorId', encrypted_model_fields.fields.EncryptedCharField(null=True, verbose_name='zaszyfrowany id doktora')),
                ('regionId', models.CharField(choices=[('01', 'dolnośląskie (Wrocław)'), ('02', 'kujawsko-pomorskie (Bydgoszcz)'), ('03', 'lubelskie (Lublin)'), ('04', 'lubuskie (Zielona Góra)'), ('05', 'łódzkie (Łódź)'), ('06', 'małopolskie (Kraków)'), ('07', 'mazowieckie (Warszawa)'), ('08', 'opolskie (Opole)'), ('09', 'podkarpackie (Rzeszów)'), ('10', 'podlaskie (Białystok)'), ('11', 'pomorskie (Gdańsk)'), ('12', 'śląskie (Katowice)'), ('13', 'świętokrzyskie (Kielce)'), ('14', 'warmińsko-mazurskie (Olsztyn)'), ('15', 'wielkopolskie (Poznań)'), ('16', 'zachodniopomorskie (Szczecin)')], verbose_name='id lokalizacji')),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ewuscreds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
