# Generated by Django 5.2.3 on 2025-07-07 09:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ewusaccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a09f29e9-cc8c-4e54-be99-4ecf4e34f36c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
