# Generated by Django 5.2.3 on 2025-06-30 08:13

import django.core.validators
import django.db.models.deletion
import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesel_encrypted', encrypted_fields.fields.EncryptedCharField(help_text='PESEL pacjenta w formie zaszyfrowanej', max_length=11, verbose_name='Zaszyfrowany PESEL')),
                ('pesel_search', encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='pesel_encrypted', hash_key='pesel', max_length=66, null=True, verbose_name='PESEL (wyszukiwanie)')),
                ('first_name_encrypted', encrypted_fields.fields.EncryptedCharField(max_length=100, verbose_name='Zaszyfrowane imię')),
                ('first_name_search', encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='first_name_encrypted', hash_key='first_name', max_length=66, null=True, verbose_name='Imię (wyszukiwanie)')),
                ('last_name_encrypted', encrypted_fields.fields.EncryptedCharField(max_length=100, verbose_name='Zaszyfrowane nazwisko')),
                ('last_name_search', encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='last_name_encrypted', hash_key='last_name', max_length=66, null=True, verbose_name='Nazwisko (wyszukiwanie)')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Adres email')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message="Numer telefonu musi być w formacie: '+999999999'. Dozwolone do 15 cyfr.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Numer telefonu')),
                ('date_of_birth', models.DateField(help_text='Automatycznie wyciągana z PESEL', verbose_name='Data urodzenia')),
                ('gender', models.CharField(choices=[('M', 'Mężczyzna'), ('K', 'Kobieta')], help_text='Automatycznie wyciągana z PESEL', max_length=1, verbose_name='Płeć')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data ostatniej aktualizacji')),
            ],
            options={
                'verbose_name': 'Pacjent',
                'verbose_name_plural': 'Pacjenci',
                'db_table': 'tenant_schema_patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramParticipationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation_year', models.PositiveIntegerField(help_text='Rok, w którym pacjent uczestniczył w programie', verbose_name='Rok uczestnictwa')),
                ('program_type', models.CharField(choices=[('40+', 'Program 40+'), ('inne', 'Inne programy')], max_length=10, verbose_name='Typ programu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia wpisu')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_history', to='patients.patient', verbose_name='Pacjent')),
            ],
            options={
                'verbose_name': 'Historia uczestnictwa w programie',
                'verbose_name_plural': 'Historia uczestnictwa w programach',
                'ordering': ['-participation_year', 'patient'],
                'unique_together': {('patient', 'participation_year', 'program_type')},
            },
        ),
    ]
