# Generated by Django 5.2.3 on 2025-06-30 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='first_name_encrypted',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='first_name_search',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name_encrypted',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name_search',
        ),
    ]
