# Generated by Django 5.2.3 on 2025-06-30 10:16

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_patient_first_name_encrypted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='pesel_search',
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name_encrypted',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='Zaszyfrowane imię'),
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Hash imienia używany tylko do wyszukiwania', max_length=64, null=True, verbose_name='Hash imienia do wyszukiwania'),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name_encrypted',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='Zaszyfrowane nazwisko'),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Hash nazwiska używany tylko do wyszukiwania', max_length=64, null=True, verbose_name='Hash nazwiska do wyszukiwania'),
        ),
        migrations.AddField(
            model_name='patient',
            name='pesel_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Hash numeru PESEL używany tylko do wyszukiwania', max_length=64, null=True, verbose_name='Hash PESEL do wyszukiwania'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pesel_encrypted',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='PESEL pacjenta w formie zaszyfrowanej', null=True, verbose_name='Zaszyfrowany PESEL'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['pesel_hash'], name='tenant_sche_pesel_h_efce26_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['first_name_hash'], name='tenant_sche_first_n_5a81a1_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['last_name_hash'], name='tenant_sche_last_na_eaa639_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['date_of_birth'], name='tenant_sche_date_of_b16725_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['gender'], name='tenant_sche_gender_1bc054_idx'),
        ),
        migrations.AlterModelTable(
            name='programparticipationhistory',
            table='tenant_schema_programparticipationhistory',
        ),
    ]
